# Generated by Django 4.1.3 on 2022-11-29 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Khoury_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': '1. Departments'},
        ),
    ]
