# Generated by Django 4.1.3 on 2022-11-30 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Khoury_app', '0004_alter_course_credit_alter_section_classsize_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='admin',
        ),
        migrations.AlterModelTable(
            name='advisor',
            table='advisor',
        ),
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='grade',
            table='grade',
        ),
        migrations.AlterModelTable(
            name='history',
            table='history',
        ),
        migrations.AlterModelTable(
            name='historystatus',
            table='history_status',
        ),
        migrations.AlterModelTable(
            name='message',
            table='message',
        ),
        migrations.AlterModelTable(
            name='section',
            table='section',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='ticket',
        ),
        migrations.AlterModelTable(
            name='ticketstatus',
            table='ticket_status',
        ),
    ]
