# Generated by Django 4.1.3 on 2022-11-30 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Khoury_app', '0005_alter_admin_table_alter_advisor_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'terms',
                'db_table': 'term',
            },
        ),
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterModelOptions(
            name='advisor',
            options={'verbose_name_plural': 'Advisors'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'verbose_name_plural': 'Grades'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'Histories'},
        ),
        migrations.AlterModelOptions(
            name='historystatus',
            options={'verbose_name_plural': 'History Status'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterModelOptions(
            name='ticketstatus',
            options={'verbose_name_plural': 'Ticket Status'},
        ),
        migrations.RemoveField(
            model_name='section',
            name='year',
        ),
        migrations.AlterField(
            model_name='section',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Khoury_app.term'),
        ),
    ]
