# Generated by Django 4.1.3 on 2022-11-30 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Khoury_app', '0006_term_alter_admin_options_alter_advisor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Khoury_app.grade'),
        ),
    ]
