# Generated by Django 4.1.3 on 2022-11-30 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Khoury_app', '0008_alter_student_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
