# Generated by Django 4.1.3 on 2022-12-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Khoury_app', '0010_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='request',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
