# Generated by Django 4.1.3 on 2022-12-02 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Khoury_app', '0011_ticket_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_id', to='Khoury_app.student'),
        ),
    ]
