# Generated by Django 4.1.3 on 2022-12-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Khoury_app', '0013_alter_ticket_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(),
        ),
    ]
