# Generated by Django 4.1.3 on 2022-12-04 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Khoury_app', '0015_alter_ticket_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Khoury_app.student'),
        ),
    ]
