# Generated by Django 4.1.3 on 2022-12-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Khoury_app', '0016_section_location_alter_ticket_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
