# Generated by Django 4.1.3 on 2022-12-07 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Khoury_app', '0018_alter_student_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Khoury_app.department'),
        ),
    ]
